### ISSUE TITLE
Executing the task according to the input message/command

### ISSUE THREAD

**Issue by muskankhedia** [Harkishen-Singh/Jarvis-personal-assistant#10]
After the message has been sent to the server, now the software should itself detect for the specific keywords from the input message and execute different tasks based on the syntax decided for different categories of the task.

Some of the examples of the commands are:
1. **google search <text to be searched>** should perform the task of searching the particular text in google and displaying it to the user.
2. **youtube search <text to be searched>** should perform the task of searching the particular text in youtube and suggesting the videos according to the provided input.
3. such some commands for git.

And syntax for other possible options can be suggested and discussed in the comment section.

**Comment by Harkishen-Singh** [comment]
May be, we could make different issues for those actions which could be resolved in the front view, with angular, like **send** to send the message to the service. Let this issue contain only the service functionality.

Please make another issue for front view based commands, and transfer the ideas there, @muskankhedia

**Comment by muskankhedia** [comment]
@Harkishen-Singh pls have a review on the issue

**Comment by Harkishen-Singh** [comment]
Perfect!
