### ISSUE TITLE
Scrapping the google and bing responses directly using golang

### ISSUE THREAD

**Issue by muskankhedia** [Harkishen-Singh/Jarvis-personal-assistant#119]
Now, most of the scrapping is done using selenium browser and it is a more time taking process, so in order to reduce the processing time, it might be better to scrap directly using golang scrapping techniques.

**Comment by rakaar** [comment]
Hey @muskankhedia 
I would like to work on this issue.
Can you please give more instructions, which parts should be converted to GoLang?
In the `subprocess` folder, I saw a few JS files for fetching data.
Should I start from there?

**Comment by muskankhedia** [comment]
@rakaar In this project, in order to show the results of different queries, we scrap the data from various sites. For scrapping the results, initially the body of the HTML code of the URL is achieved using selenium and its a lot of time taking process. We want to integrate any of the packages provided by Golang to implement the entire scrapping. 

The `subprocess`  folder contains all the microservices used in the project. `fetchquery.js` helps to retrieve the HTML code from different websites.
