### ISSUE TITLE
Wrong path for background image in views/index.html

### ISSUE THREAD

**Issue by irshadjsr21** [Harkishen-Singh/Jarvis-personal-assistant#140]
The body background image currently is `./view/assest/Background/MainBG.png` which does not render on the page.

**Comment by prajwal714** [comment]
Solved the issue.

**Comment by prajwal714** [comment]
I'll Work on this.

**Comment by muskankhedia** [comment]
Sorry, this issue has already been claimed by @irshadjsr21. We will be opening more issues in 2-3 days, till then you can work on other opened issues.
