### ISSUE TITLE
Handling errors in frontend

### ISSUE THREAD

**Issue by irshadjsr21** [Harkishen-Singh/Jarvis-personal-assistant#143]
**Describe the bug**
When the API results in an error, the frontend continues to display the loading icon.
We should stop the loading icon and display an error icon along with an error notification (maybe a retry button as well).

**To Reproduce**
1. Start the frontend server
2. Stop the backend server (if it is running)
3. Type any query on the message box

**Comment by prajwal714** [comment]
I'll be working on this issue for GSSOC' 20

**Comment by muskankhedia** [comment]
@prajwal714 Thanks for your interest but according to the gssoc rules, the one who has created the issue gets assigned at the same time. You can please for some other issues or create any and work on it.
