### ISSUE TITLE
Create a Makefile for the project

### ISSUE THREAD

**Issue by muskankhedia** [Harkishen-Singh/Jarvis-personal-assistant#148]
A makefile is to be created with the set of tasks that needs to be executed, to ease the running and testing of the application.

**Comment by Aju100** [comment]
can u assigned me this

**Comment by Harkishen-Singh** [comment]
@Aju100 any updates? this should not take long.

**Comment by maheshschand** [comment]
Interested. Could you please assign me @maheshschand?

**Comment by maheshschand** [comment]
Interested. Could you please assign me @muskankhedia ?

**Comment by muskankhedia** [comment]
@maheshschand Sure.

**Comment by muskankhedia** [comment]
Soved in PR #199
