### ISSUE TITLE
Update the readme with the postman documentation link 

### ISSUE THREAD

**Issue by muskankhedia** [Harkishen-Singh/Jarvis-personal-assistant#149]
This is the link to the postman documentation for Jarvis: [Postman link](https://documenter.getpostman.com/view/6521254/SzKZrvTu?version=latest). 

Add the link to the readme.md with some explanation.

**Comment by irshadjsr21** [comment]
I'm up for it.

**Comment by VibavariG** [comment]
Please assign me this issue

**Comment by muskankhedia** [comment]
@irshadjsr21 we can only assign one issue to a participant at a time as it will create flexibility for everyone to work. Please solve the assigned issues then it will be possible to assign you for other issues.
So, assigning this issue to @Vibavari for the timing.

**Comment by muskankhedia** [comment]
@VibavariG How is the implementation going? I don't think this issue would take more than 10 mins to solve.

**Comment by Mansi145** [comment]
Hey @muskankhedia. Is this issue still up for a grab? I'd like to work on this.

**Comment by muskankhedia** [comment]
@Mansi145 Yaa sure. You can take it.

**Comment by CSElonewolf** [comment]
Hello @muskankhedia good to see a new work on README.md I am up for it will update it within 1 hour.Please asssign this to me :)

**Comment by CSElonewolf** [comment]
@muskankhedia assign this to me..

**Comment by ananyaarun** [comment]
Hey @CSElonewolf , This issue was assigned to @Mansi145 .
Next time ensure you get an issue assigned to yourself before opening a PR for it.
Thanks !

**Comment by Harkishen-Singh** [comment]
should we close this?

**Comment by CSElonewolf** [comment]
> Hey @CSElonewolf , This issue was assigned to @Mansi145 .
> Next time ensure you get an issue assigned to yourself before opening a PR for it.
> Thanks !

Mam actually I didn't see anyone assigned under the assignee when I commented.Therefore I felt that it is still open.

**Comment by muskankhedia** [comment]
@CSElonewolf It's not necessary for there to be assignee, please go through the commits in the issue and the date and time this has been taken and assigned to someone. As if some issues had been mentioned much longer can be taken by other participant.
