### ISSUE TITLE
Scrapping for the google images requests using golang 

### ISSUE THREAD

**Issue by muskankhedia** [Harkishen-Singh/Jarvis-personal-assistant#150]
**Is your feature request related to a problem? Please describe.**
Presently the scrapping for the google images is done using the selenium browser,  now we are revamping the application and level up all the scrapping to be done using golang. As using various different dependency for different features is making the work difficult and also increases the size of the application.

**Describe the solution you'd like**
The scrapping of the google images requests to be updated and implemented using the golang scrapping packages. One of them package implemented presently for the google and bing scrapping is `goquery`. Other recommendations of golang packages are most welcome.

**Comment by gunjanmimo** [comment]
@muskankhedia can I take this issue?

**Comment by muskankhedia** [comment]
Sure. Go ahead.

**Comment by irshadjsr21** [comment]
I'd like to take this up if it's not assigned yet.

**Comment by muskankhedia** [comment]
@irshadjsr21 This issue has been presently assigned to @gunjanmimo. Please take up any other issue for now.

@gunjanmimo How is the implementation going?

**Comment by gunjanmimo** [comment]
Mam, I was unable to work for my exam, now I am working on this issue. I think I will complete today

**Comment by Harkishen-Singh** [comment]
@gunjanmimo any updates on this would be most helpful.

**Comment by muskankhedia** [comment]
@gunjanmimo Any updates?
