### ISSUE TITLE
Scrapping for Medicine and symptoms information using golang

### ISSUE THREAD

**Issue by Harkishen-Singh** [Harkishen-Singh/Jarvis-personal-assistant#151]
The current implementation is done in nodejs. We want to unify this experience and hence want them in golang. This was earlier done by selenium in node but selenium being difficult and unethical, cannot be used for works involving stability of the app.

Hence, convert the existing method into golang and scrape them rather than using selenium.

**Comment by irshadjsr21** [comment]
I'm up for it.

**Comment by muskankhedia** [comment]
Sure. Go ahead.

**Comment by Diu2912** [comment]
Can I do this one?

**Comment by muskankhedia** [comment]
This issue has already been assigned to @irshadjsr21

**Comment by Diu2912** [comment]
Okay Mam

**Comment by ananyaarun** [comment]
Hey @muskankhedia , Can we close this issue ? looks like there is a merged PR

**Comment by muskankhedia** [comment]
@ananyaarun Thanks for looking at it. But the PR has only solved the scrapping part for the medicine search, the symptoms scrapping has to be yet implemented.

**Comment by Harkishen-Singh** [comment]
@irshadjsr21 are you still working on symptoms scrapping?

**Comment by irshadjsr21** [comment]
Yeah, working on it.
