### ISSUE TITLE
Refractor all existing strings to proper config.json

### ISSUE THREAD

**Issue by Harkishen-Singh** [Harkishen-Singh/Jarvis-personal-assistant#154]
We have many configurations like priority string [link](https://github.com/Harkishen-Singh/Jarvis-personal-assistant/blob/a72b0db735fc928de3402752dd4761e370c6863b/service/controllers/messages.go#L98), etc., can be added to a config.json file and then it can be loaded into the system during start.

**Comment by irshadjsr21** [comment]
I'm up for it.

**Comment by muskankhedia** [comment]
Sure. Go ahead.

**Comment by irshadjsr21** [comment]
@Harkishen-Singh @muskankhedia Should I include all the search variants in the file `service/controllers/searchVariants.go` into the `config.json`?

**Currently added**
- User Agents from file `service/controllers/common.go`
- Keywords Priority from file `service/controllers/messages.go` 

Let me know if something else also has to be added there.

**Comment by muskankhedia** [comment]
@irshadjsr21 for the timing don't add the search variants in the file `service/controllers/searchVariants.go`. I think there isn't anything more to be added.

**Comment by ikatheria** [comment]
AFTER running this command cd service && go run main.go we are getting error - Error ▶ ERRO 001 open static/config.json: no such file or directory.

Please help.
