### ISSUE TITLE
Saving logs in secondary storage.

### ISSUE THREAD

**Issue by Harkishen-Singh** [Harkishen-Singh/Jarvis-personal-assistant#159]
Logs are necessary to debug. They would be intensively used in further updates. Hence, these logs should be stored.

**Comment by irshadjsr21** [comment]
I'd like to take this up.

**Comment by muskankhedia** [comment]
Sure.

**Comment by irshadjsr21** [comment]
@muskankhedia The PR has been merged, I think we can close this issue now.
