### ISSUE TITLE
Jarvis Home Page UI Change

### ISSUE THREAD

**Issue by lalitmee** [Harkishen-Singh/Jarvis-personal-assistant#161]
**Home Page**
![Selection_005](https://user-images.githubusercontent.com/10762218/75755936-a7f9f100-5d55-11ea-9683-a212f8b04625.png)

We need to come up with some **mockups** for the same and then we will select the mockup which will be good for the **User Experience** and will implement that.

**Two things to keep in mind**:
- We would prefer it if you can use [Figma](https://www.figma.com/) for creating mockups and when you think you are done, raise the PR with a link of the **Figma Mockup**. 
- If you like to use any other platform for mockups please do the same thing. Create PR with the mockup.

**Comment by SubCoder1** [comment]
I am interested to take up this issue @lalitmee 

I would like to see my mockup using HTML, CSS and Bootstrap instead of Figma since I have not used the later tool.

**Comment by lalitmee** [comment]
@SubCoder1 , still you will be having some design in your mind that you wanna do this. 
Actually why we are asking for mockup is because if we will directly implement it then it will be a lot of effort. That's why I think we should try some mockups first then we will go ahead and select one.

You can use whatever you want for the mockup. :+1:

**Comment by algokun** [comment]
I would like to contribute to this one. can anyone assign this issue to me??

**Comment by SubCoder1** [comment]
@lalitmee ok I can create and show you the mockup in CodePen or JSfiddle.

**Comment by muskankhedia** [comment]
@subcoder1 you can go ahead with the work, after the design is ready you can share the link in the form of pull request. You can create a file with the name 'ui-design-<section-name>-<github-username>' and add the link on it, in the folder ui-designs.

**Comment by muskankhedia** [comment]
@algokun, as per rules, as @subcoder1 has commented first to the issue, the issue gets assigned to him. There are many other UI designing issues in the project, you can work on them. Please make a comment before working so I can assign it to you.

**Comment by Diu2912** [comment]
I want to contribute this one ...Can you assign to me ?

**Comment by muskankhedia** [comment]
@Diu2192 Welcome to the project. This issue has already been assigned to @subCoder1, you can look for other issues and comment on it, you are interested to work on.

**Comment by muskankhedia** [comment]
@SubCoder1 How is the implementation going?

**Comment by SubCoder1** [comment]
@muskankhedia it's almost done! I'll send a PR today at night as I'm out right now :)

**Comment by muskankhedia** [comment]
Cool

**Comment by SubCoder1** [comment]
@muskankhedia I've shared two Figma links in my PR, two has different prototypes for the UI. Kindly review and suggest any changes I need to make :sweat_smile:

**Comment by Diu2912** [comment]
okay i will review it .. Can you please tell me how to work on github means
how i can score in that

**Comment by SubCoder1** [comment]
@Diu2912 participants can't review PRs, only mentors can.

**Comment by Diu2912** [comment]
Okay Sir !!!

**Comment by muskankhedia** [comment]
@Diu2912 The PR reviews are meant for mentors. And if you are new to Github and some help you can message in the #slackhelp channel or direct message any mentor. Please don't spam the issues or PRs by making such unnecessary comments. Please delete all your messages from different issues and PRs.
