### ISSUE TITLE
Jarvis Get Help UI Change

### ISSUE THREAD

**Issue by lalitmee** [Harkishen-Singh/Jarvis-personal-assistant#162]
**Get Help** Section
![Selection_007](https://user-images.githubusercontent.com/10762218/75756000-cd86fa80-5d55-11ea-9774-3ab009d73239.png)

We need to come up with some **mockups** for the same and then we will select the mockup which will be good for the **User Experience** and will implement that.

**Two things to keep in mind**:
- We would prefer it if you can use [Figma](https://www.figma.com/) for creating mockups and when you think you are done, raise the PR with a link of the **Figma Mockup**. 
- If you like to use any other platform for mockups please do the same thing. Create PR with the mockup.

**Comment by robot-with-feelings** [comment]
@lalitmee i'd like to work on this, i have knowledge of figma

**Comment by muskankhedia** [comment]
@robot-with-feelings Sure. Go ahead.
