### ISSUE TITLE
Update Readme.md with  the organizations the project has been selected

### ISSUE THREAD

**Issue by muskankhedia** [Harkishen-Singh/Jarvis-personal-assistant#168]
The project **_Jarvis Personal Assistant_** has been selected many times in various coding programmes like starting from, KWoC-2019, JMoC-2019 and now GSSoC-2020. All these needs to be updated in the Readme, under a new section _**Achievements(other suggestions are most welcome)**_ with the proper logos.

**Comment by CSElonewolf** [comment]
hello @muskankhedia mam,I am very much interested working on this issue.Kindly assign me this issue.I have already collected the logo links and am ready to update the README section and push it by today itself.Thank You

**Comment by muskankhedia** [comment]
@CSElonewolf Sure.

**Comment by CSElonewolf** [comment]
Suggestion:-

1.Will add a logo all the competitions and write a little description of them..

**Comment by muskankhedia** [comment]
Yaa sure. Good to go.

**Comment by CSElonewolf** [comment]
Mam @muskankhedia please review the PR and let me know if any change is to be made.

**Comment by muskankhedia** [comment]
@CSElonewolf I have reviewed the PR and made the comment. Please make the necessary changes.
