### ISSUE TITLE
Change UI

### ISSUE THREAD

**Issue by Diu2912** [Harkishen-Singh/Jarvis-personal-assistant#175]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by muskankhedia** [comment]
@Diu2912 This is not a testing repo. Closing this issue and stop spamming in the repository.

**Comment by Diu2912** [comment]
Yes Mam!! Sorry i don't know how to work with github ..I will not do again

**Comment by muskankhedia** [comment]
It's fine. And please don't call me ma'am, I am also a student. The GSSoC programme is not a competition, its for learning and specifically for newcomers. Make some of your own repos, work on it, learn how to use GitHub. Then start contributing to any project.

**Comment by Diu2912** [comment]
Yeah Sure !! I will learn first then come back in contributing again ..
