### ISSUE TITLE
Enhancing the recent queries heading in the desktop app

### ISSUE THREAD

**Issue by muskankhedia** [Harkishen-Singh/Jarvis-personal-assistant#186]
The recent queries heading in the desktop app is quite unclear as of now and maybe confused with a button.

**Comment by robot-with-feelings** [comment]
can i work on this, using Figma?

**Comment by muskankhedia** [comment]
Sure.

**Comment by ananyaarun** [comment]
Hey @robot-with-feelings , any update on this issue ?

**Comment by robot-with-feelings** [comment]
Yes @ananyaarun! Will send a PR in a while.
