### ISSUE TITLE
Implementing the meaning search 

### ISSUE THREAD

**Issue by muskankhedia** [Harkishen-Singh/Jarvis-personal-assistant#210]
**Is your feature request related to a problem? Please describe.**
As the service has now been revamped using NodeJs. The features like yahoo search have to be implemented with the proper scrapping of data from the oxford dictionary website.

**Describe the solution you'd like**
To show the meaning of the data, on query search `meaning <word>`. We are using the library CherrioJs to implement the same and

**Additional context**
You can also refer to the previous code to know about the requirements and have an idea of scrapping.
For now, submit the PR to the node-master branch, we will soon be merging it with the master branch when most of the basic features have been implemented.

**Comment by irshadjsr21** [comment]
I'd like to take this up

**Comment by muskankhedia** [comment]
Sure. Go ahead.
