### ISSUE TITLE
change of listening loader icon

### ISSUE THREAD

**Issue by Harkishen-Singh** [Harkishen-Singh/Jarvis-personal-assistant#26]
present situation

![Screenshot from 2019-03-29 18-21-18](https://user-images.githubusercontent.com/33792202/55233774-92c83880-524f-11e9-86cd-7270d0285c06.png)

the perfect situation would be the loader **aligned next to the Mic**.

**Comment by Subham-Mishra** [comment]
Its done in my commit

**Comment by Subham-Mishra** [comment]
![Capture](https://user-images.githubusercontent.com/35756816/55240403-d7a79b80-525e-11e9-8daf-1b7aa45f8596.JPG)
