### ISSUE TITLE
use of Dice's coefficient to measure the nearest possible string comparison condition

### ISSUE THREAD

**Issue by Harkishen-Singh** [Harkishen-Singh/Jarvis-personal-assistant#65]
it is almost impossible to write the conditional string checks, so **Dice's coefficient** can help find the most matching condition, from a given set of conditions. The design of the algorithm should be clean and tidy so that it could satisfy most conditions.

**Comment by muskankhedia** [comment]
Yaa understood I will try my best to write a clean code satisfying most of the condition. 
Thanks for assigning the issue.

**Comment by Harkishen-Singh** [comment]
Always welcome
