### ISSUE TITLE
Empty messages prevention

### ISSUE THREAD

**Issue by C-Anirudh** [Harkishen-Singh/Jarvis-personal-assistant#67]
The current implementation of sending messages allows us to send empty messages as shown below:
![emptymsg](https://user-images.githubusercontent.com/40494926/55567310-028c6680-571b-11e9-8f6b-fec141cb41b0.png)
Ideally, empty messages shouldn't be allowed and `Type a message ...` should be a label, instead of text in the input field.

**Comment by C-Anirudh** [comment]
@Harkishen-Singh Can I work on this?

**Comment by Harkishen-Singh** [comment]
@C-Anirudh  thanks for showing your interest! please go ahead.
