### ISSUE TITLE
Displaying error message for searches when there is no Internet Connectivity

### ISSUE THREAD

**Issue by C-Anirudh** [Harkishen-Singh/Jarvis-personal-assistant#70]
Currently, when we attempt searches without Internet Connectivity, an empty output is shown.
![netError(1)](https://user-images.githubusercontent.com/40494926/55583285-2497e000-573f-11e9-9498-525e939c4be4.png)
Ideally, a proper error message stating that there is no Internet Connnectivity should be displayed.

**Comment by C-Anirudh** [comment]
@Harkishen-Singh Can I work on this?

**Comment by Harkishen-Singh** [comment]
sure!
