### ISSUE TITLE
updating README.md

### ISSUE THREAD

**Issue by Harkishen-Singh** [Harkishen-Singh/Jarvis-personal-assistant#72]
The README.md looks outdated and needs to be maintained with the current features. At the same time, the view should be attractive and appealing.

We have almost 17 unique visitors and 54 unique clones and would like to keep up the popularity of the project by increasing the interactiveness of the first screen of the repository.

Sample readme outlook [sample readme for jarvis](https://github.com/sukeesh/Jarvis/blob/master/README.md)

**Comment by muskankhedia** [comment]
Done.
