### ISSUE TITLE
Prevent empty queries

### ISSUE THREAD

**Issue by C-Anirudh** [Harkishen-Singh/Jarvis-personal-assistant#74]
In the chat interface, when we type google, yahoo, bing, etc without a query following it, an empty message is displayed.
![queryErr(1)](https://user-images.githubusercontent.com/40494926/55624680-5010de00-57c4-11e9-8c35-61e0fbcbddf5.png)

Ideally, empty queries should be dealt with properly and empty messages should be prevented

**Comment by C-Anirudh** [comment]
@Harkishen-Singh May I work on this?

**Comment by Harkishen-Singh** [comment]
Sure!
