### ISSUE TITLE
Reducing code redundancy in 'main.html'

### ISSUE THREAD

**Issue by C-Anirudh** [Harkishen-Singh/Jarvis-personal-assistant#78]
Currently, everytime we add a new message/conversation , we have to manually add the front-end for displaying it. This is not suited as the application grows bigger. The code should follow DRY principle.
`We must have a general template to display all messages`

**Comment by C-Anirudh** [comment]
@Harkishen-Singh I would like to try my hand in making this better

**Comment by Harkishen-Singh** [comment]
Yeah. A generalised condition bsed on type of message and components should help
