### ISSUE TITLE
Adding a help button at the bottom of the left panel 

### ISSUE THREAD

**Issue by muskankhedia** [Harkishen-Singh/Jarvis-personal-assistant#85]
There are many predefined commands for different kinds of the task and it will be increasing every day with the increase of features in the project. In order to provide a complete syntax data, a help button could be added at the bottom of the left panel, on clicking on it a modal will be displayed with all the syntax written on it.

**Comment by C-Anirudh** [comment]
I think it would be nice, if we could make it like Gitter's markdown help.

**Comment by muskankhedia** [comment]
Yaa.. nice idea.
