### ISSUE TITLE
Release beta - 2

### ISSUE THREAD

**Issue by Harkishen-Singh** [Harkishen-Singh/Jarvis-personal-assistant#95]
Second beta release of the project, do that the users could directly download and run the code, without bothering about the dependencies are deployment.

Further, a number of critical and necessary features have been added since last release, hence making the project useful for the users.

**Comment by Harkishen-Singh** [comment]
@muskankhedia  please have a look!

**Comment by muskankhedia** [comment]
Yaa... I will do it today.

**Comment by muskankhedia** [comment]
I have released the beta-2 version of Jarvis-Personal-Assistant. @Harkishen-Singh please have a look.
